data = [
    {
        question: "What is your element?",
        a1: "Fire",
        a2: "Earth",
        a3: "Water",
        a4: "Air",
        imgSrc: "https://images.unsplash.com/photo-1496347315686-5f274d046ccc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80",
    },

    {
        question: "You are lost inside a forest and you meet a pathway, which path do you choose?",
        a1: "The route towards the castle",
        a2: "The route towards the jungle",
        a3: "The route towards the sea",
        a4: "The route towards the sky",
        imgSrc: "https://images.unsplash.com/photo-1562948853-963f5ab6a434?ixlib=rb-1.2.1&auto=format&fit=crop&w=1334&q=80",
    },

    {
        question: "You open a treasure chest and are granted a chance to take one item, which item do you choose:",
        a1: "The Heart of Dragon",
        a2: "A Soul of The Undead",
        a3: "The Eyes of The Sea",
        a4: "The Holy Blood of God",
        imgSrc: "https://images.unsplash.com/photo-1553991562-9f24b119ff51?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1274&q=80",
    },

    {
        question: "Who are you?",
        a1: "A pirate on its journey to the neverland",
        a2: "A princess in its locked tower",
        a3: "A queen with a tainted heart",
        a4: "A witch with a wicked sin",
        imgSrc: "https://images.unsplash.com/photo-1521616210349-dbec8efd13b4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80",
    },

    {
        question: "Your chosen cards?",
        a1: "The King",
        a2: "The Jack",
        a3: "The Queen",
        a4: "The Ace",
        imgSrc: "https://images.unsplash.com/photo-1532152734721-b08cb57943aa?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80",
    },

    {
        question: "Sign of soul?",
        a1: "The Heart",
        a2: "The Clover",
        a3: "The Diamond",
        a4: "The Spade",
        imgSrc: "https://images.unsplash.com/photo-1542598688-5597ff6d3cf4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1789&q=80",
    },

    {
        question: "You are opposed to a very strong warrior in the bridge and you have to fight them to get over it",
        a1: "Bring on a 1-1 battle",
        a2: "Negotiate a peaceful way",
        a3: "Manipulate or mislead them",
        a4: "Just ignore them",
        imgSrc: "https://images.unsplash.com/photo-1560090628-5fa60a573240?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1474&q=80",
    },
    {
        question: "What is your favourite cake?",
        a1: "Brownie",
        a2: "Moon cake",
        a3: "Black forest cake",
        a4: "Red velvet",
        imgSrc: "https://images.unsplash.com/photo-1426869884541-df7117556757?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80",
    },
    {
        question: "Which is your favourtie animal?",
        a1: "Lion",
        a2: "Dog",
        a3: "Fox",
        a4: "Owl",
        imgSrc: "https://images.unsplash.com/photo-1562821090-797af8a39e9b?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80",
    },
    {
        question: "What is your dream job among this:",
        a1: "Politics",
        a2: "Education",
        a3: "Art",
        a4: "IT",
        imgSrc: "https://images.unsplash.com/photo-1462206092226-f46025ffe607?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1506&q=80",
    },
    {
        question: "Who are you?",
        a1: "The leader",
        a2: "The ambassador ",
        a3: "The supporter ",
        a4: "The rogue",
        imgSrc: "https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80",
    },
    {
        question: "Choose a card?",
        a1: "The World",
        a2: "The Lover",
        a3: "The Empress",
        a4: "The Hermit",
        imgSrc: "https://images.unsplash.com/photo-1562532755-1c8e8e323201?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80",
    },
    {
        question: "What is your house?",
        a1: "Dragon",
        a2: "Griffin",
        a3: "Vulpes",
        a4: "Succubus",
        imgSrc: "https://images.unsplash.com/photo-1504346879257-9d899883589f?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80",
    },
    {
        question: "Choose your weapon",
        a1: "The potion that can grant you power",
        a2: "The potion that can help other people. ",
        a3: "The potion that can grant you eternal beauty and youth",
        a4: "The potion that give you wisdom",
        imgSrc: "https://images.unsplash.com/photo-1546201483-8886694038aa?ixlib=rb-1.2.1&auto=format&fit=crop&w=1500&q=80",
    },
    {
        question: "What is your favourite weather?",
        a1: "Sunny",
        a2: "Stormy",
        a3: "Cloudy",
        a4: "Rainy",
        imgSrc: "https://images.unsplash.com/photo-1529281528138-fbe93b7d25a4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1338&q=80",
    },
]